// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/mobile-detect/mobile-detect.d.ts
declare class MobileDetect {
	
	constructor(userAgent: string, maxPhoneWidth?: number);
	
	is(key: string): boolean;
	match(pattern: string|RegExp): boolean;
	mobile(): string;
	mobileGrade(): string;
	os(): string;
	phone(): string;
	tablet(): string;
	userAgent(): string;
	version(value: string): number;
	versionStr(value: string): string;
}